SELECT
	CASE
		WHEN FLOOR(DATE_PART('YEAR',
			AGE(NOW(), birthday))/10)*10 < 18 THEN 18	
		ELSE FLOOR(DATE_PART('YEAR',
			AGE(NOW(), birthday))/10)*10
	END AS AGE_GROUP,
	COUNT(id) AS "NUMBER"
FROM
	customers
GROUP BY AGE_GROUP
LIMIT 10;

